### ISSUE TITLE
Create Tag Functionality

### ISSUE THREAD

**Issue by CohenCalvert** [CMPUT301F23T24/KeepItAll#76]

**Comment by Silin5** [comment]
Add and delete tag works!

**Comment by Silin5** [comment]
Firebase was set up!

**Comment by Silin5** [comment]
-Created global Tags Manager to manage the tags for all items. This class holds a Map where each key is an Item identifier, and the value is a list of Tag objects.
-Update ItemTagsActivity to use TagsManager since ItemTagsActivity was primarily dealing with displaying and managing tags.
-Passed the item's name along with the intent when starting AddTagActivity from ItemTagsActivity.

**Comment by Silin5** [comment]
Each Item can have multiple tags, and tags can be shared across different items right now!
